# Generated by Django 2.2.4 on 2019-08-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_friendlist_friend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='Friend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='instagram.SignUp'),
        ),
    ]
